name: 🐛 Bug Report
description: Report a bug or unexpected behavior in SAM
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before You Continue...
        
        **Have you checked these resources first?**
        - 📚 [Documentation](https://www.syntheticautonomicmind.org)
        - 💬 [GitHub Discussions](https://github.com/SyntheticAutonomicMind/SAM/discussions) - For questions and support
        - 🔍 [Existing Issues](https://github.com/SyntheticAutonomicMind/SAM/issues) - Your issue may already be reported
        
        **Common issues with quick fixes:**
        - **"Model not found"** → Check `~/Library/Caches/sam/models/` directory
        - **"API key invalid"** → Verify key in Preferences → API Configuration
        - **"Wake word not working"** → Enable microphone permissions in System Settings
        - **"Image generation fails"** → Check Python environment and Stable Diffusion model installation
        
        If you've tried troubleshooting and still have an issue, please continue below.

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you've tried these steps
      options:
        - label: I have read the [documentation](https://www.syntheticautonomicmind.org)
          required: true
        - label: I have searched [existing issues](https://github.com/SyntheticAutonomicMind/SAM/issues)
          required: true
        - label: I have checked [GitHub Discussions](https://github.com/SyntheticAutonomicMind/SAM/discussions)
          required: true
        - label: I have tried restarting SAM
          required: true
        - label: I am using the latest version of SAM
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Open SAM
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: SAM should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, SAM...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Which area is affected?
      description: Select the component that's experiencing issues
      options:
        - Chat Interface
        - Voice Control (Wake Word / Speech Recognition / TTS)
        - Image Generation (Stable Diffusion)
        - Local Models (MLX / llama.cpp)
        - API Configuration
        - File Operations / Tools
        - Memory / RAG System
        - Document Export (PDF / DOCX / PPTX)
        - Web Research
        - Installation / Setup
        - Performance / Crashes
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SAM Version
      description: What version of SAM are you using? (Check "About SAM" or release tag)
      placeholder: "e.g., 20251221.1"
    validations:
      required: true

  - type: input
    id: macos
    attributes:
      label: macOS Version
      description: What version of macOS are you running?
      placeholder: "e.g., macOS 14.2 (Sonoma)"
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      description: What Mac are you using?
      options:
        - Apple Silicon (M1/M2/M3/M4)
        - Intel Mac
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider (if relevant)
      description: Which AI provider were you using when the issue occurred?
      options:
        - Not applicable
        - GitHub Models
        - OpenAI
        - Anthropic (Claude)
        - Google (Gemini)
        - DeepSeek
        - Grok
        - Local MLX Model
        - Local llama.cpp (GGUF)
        - Other/Custom

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output. 
        Logs can be found at: `~/Library/Logs/SAM/` or in Console.app searching for "SAM"
        **Tip:** Remove any API keys or personal information before pasting!
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Did this work in a previous version?
        - Have you modified any configuration files?
        - Are there any error messages in the UI?
